[package]
name = "rtop"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
num_cpus = "1.16.0"
ratatui = "0.29.0"
sysinfo = "0.33.1"
thiserror = "2.0.11"
tokio = { version = "1.43.0", features = ["full", "rt"] }
